# Generated by Django 3.2.16 on 2022-12-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='user')),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
